trigger:
  branches:
    include:
      - master


pool:
  name: 'MySelfHostedPool'





variables:

  - group: vg-MonolithAPI-prod 





stages:

# =========================
#  BUILD STAGE
# =========================
- stage: Build
  displayName: "Build & Publish"
  jobs:
    - job: BuildJob
      steps:
        - task: UseDotNet@2
          displayName: "Install .NET SDK"
          inputs:
            packageType: 'sdk'
            version: '$(dotnetVersion)'
        
        - task: FileTransform@2
          inputs:
            folderPath: $(System.DefaultWorkingDirectory)
            jsonTargetFiles: '**/appsettings.json'
            
        - task : DotNetCoreCLI@2
          displayName: 'restore packages'
          inputs:
            command : restore
              
        - task : DotNetCoreCLI@2
          displayName: 'building project files' 
          inputs:
            command : build
            arguments: '--configuration $(buildConfiguration) --no-restore' 
        
        - task : DotNetCoreCLI@2
          displayName: 'publishing'
          inputs:
            command : publish
            publishWebProjects: false
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
            zipAfterPublish: true 
        
        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop


# =========================
#  DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: "Deploy to Azure Web App"
  dependsOn: Build

  jobs:
    - deployment: DeployWebApp
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: AzureWebApp@1
                displayName: "Deploy to Azure"
                inputs:
                  azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
                  appName: '$(WEB_APP_NAME)'
                  package: '$(Pipeline.Workspace)/drop/MonolithAPI.zip'
                  resourceGroupName: '$(RESOURCE_GROUP)'
                  appType: 'webApp'